### ISSUE TITLE
Exciting project!

### ISSUE THREAD

**Issue by kmatch98** [markb139/pico_logic#1]
I just ran across your project while trying to decipher how to use USBTMC in tinyUSB, for the exact same purposes as you are doing.  I'm writing to see if there is a way that we can collaborate. 

I'm trying to extend the TinyLogicFriend project to be able to use any microcontroller board as a logic analyzer along with sigrok.  

I've done some digging into sigrok and have been making some progress.  I've been able to build a sigrok hardware driver and decipher all the USB constructors.  I'm just starting to look into how to do the USB interface and the microcontroller side and ran across your repository.  

It seems like you have similar objectives, so if we could break the task into pieces it might help us get further along.  Below is a link to my repo and my overview of how I'm proceeding.  

https://github.com/kmatch98/tinylogicfriend/issues/1

**Comment by markb139** [comment]
Hi,
I've now pushed up my changes to libsigrok into a forked repository.
It's all working, but I'm still in a learning phase as I've not really worked in the embedded world and it's a long time since I wrote C code :)

There several things that need to be added. I'll create some issues later. The main thing I need to add is handling of triggers.

**Comment by kmatch98** [comment]
Thanks again for this work, I’m learning a lot by reviewing your code. I’ll close this issue now and will keep an eye on your additions and the issues you raise.
